version: "3"
services:
  ruby:
    image: ruby:latest
    command: bash -c 'gem install discordrb && gem install dotenv && ruby bot.rb'
    working_dir: /usr/app/
    volumes:
      - ./:/usr/app/
    networks:
      - projekt7_network
networks:
  projekt7_network:
    external: true
